-- 하루 가게 — 시설 안내 줄글 칸 (2026-09-14)
--
-- 대표: *「여기는 태그도 좋은데, 줄글도 쓸 수 있는 구조로 짜야 할 거 같아.
--        (2)태그는 사용 가능한 시설을 추가할 때 키워드로 추가되게
--        (3)줄글은 시설 안내, multi text input으로 등록할 때 등록하게」*
--
-- ⭐태그(`facilities`)는 **고르는 것**이고 이 칸은 **읽는 것**이다. 태그로는 「빔프로젝터 있음」까지만
--   말할 수 있고, 「HDMI 케이블은 없어서 가져오셔야 해요」는 줄글이라야 한다. 둘은 대체재가 아니다.
--
-- 🚨 실행: Supabase 대시보드 > SQL Editor 에 이 파일만 붙여넣기. 여러 번 실행해도 안전하다.
alter table spaces add column if not exists facilities_note text not null default '';
